const now = Date.now();

export interface InterviewQuestionSeed {
  id: string;
  area: string;
  difficulty: "junior" | "mid" | "senior";
  category?: string;
  question: string;
  answer: string;
  tags: string[];
  favorite?: boolean;
  createdAt: number;
}

export const seedInterviewQuestions: InterviewQuestionSeed[] = [
  // Angular
  {
    id: "iq_ang_1",
    area: "frontend",
    difficulty: "junior",
    category: "Angular",
    question: "What is the difference between Components and Directives in Angular?",
    answer: "Component: a directive with a template. It defines a view and controls its logic via templates/styles. Directive: attaches behavior, modifies DOM, or alters layout of elements without a dedicated template. Categories of directives: structural (alter DOM layout, e.g., *ngIf) and attribute (alter appearance/behavior, e.g., ngStyle).",
    tags: ["angular", "components", "directives"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_ang_2",
    area: "frontend",
    difficulty: "mid",
    category: "Angular",
    question: "Explain Angular's dependency injection (DI) system and hierarchical injectors.",
    answer: "Angular has a hierarchical DI system. Injectors are created at module, component, or directive levels. Resolution bubbles up: if a dependency isn't found at the current level, it checks the parent injector up to the root/platform injector. Use `providedIn: 'root'` for singletons, or list in `providers: []` of a component to scope the dependency to that component and its children.",
    tags: ["angular", "dependency-injection", "architecture"],
    createdAt: now,
  },
  {
    id: "iq_ang_3",
    area: "frontend",
    difficulty: "mid",
    category: "Angular",
    question: "What are Angular Signals and how do they differ from RxJS?",
    answer: "Signals (Angular 16+) are reactive values that notify consumers when they change. Unlike RxJS observables, Signals do not require subscriptions/unsubscriptions, are synchronous, always have a value, and trigger change detection surgically without zones. Use Signals for state management and local UI reactivity; use RxJS for asynchronous event streams, HTTP requests, and complex operator piping.",
    tags: ["angular", "signals", "rxjs", "reactivity"],
    createdAt: now,
  },
  {
    id: "iq_ang_4",
    area: "frontend",
    difficulty: "mid",
    category: "Angular",
    question: "Explain Change Detection in Angular (Default vs OnPush).",
    answer: "Default: Angular checks all components from top to bottom on any event/async operation (zones). OnPush: component is only checked when input references change (@Input), an event handler inside triggers, or change detection is run manually (cdr.markForCheck()). OnPush improves performance by skipping unchanged subtrees.",
    tags: ["angular", "change-detection", "performance"],
    createdAt: now,
  },

  // Backend
  {
    id: "iq_be_1",
    area: "backend",
    difficulty: "junior",
    category: "Databases",
    question: "What is the difference between SQL and NoSQL databases?",
    answer: "SQL: relational, structured table format, predefined schema, supports complex JOINs and transaction safety (ACID). Best for transactional, structured systems (e.g., banking). NoSQL: non-relational, flexible schema (documents, key-value, graph), optimized for horizontal scaling and rapid iteration. Best for unstructured data, high write throughput.",
    tags: ["databases", "sql", "nosql"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_be_2",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is database indexing and how does it improve query performance?",
    answer: "An index is a data structure (typically B-Tree) that stores pointer references to table rows, allowing queries to search in O(log N) rather than O(N) sequential scans. Indexes speed up SELECT queries with WHERE/JOIN clauses, but slow down write operations (INSERT/UPDATE/DELETE) because the index itself must be updated.",
    tags: ["databases", "indexing", "performance"],
    createdAt: now,
  },
  {
    id: "iq_be_3",
    area: "backend",
    difficulty: "mid",
    category: "API Design",
    question: "Explain the difference between REST, GraphQL, and gRPC.",
    answer: "REST: resource-oriented, standard HTTP methods (GET/POST/PUT/DELETE), JSON payload, simple but prone to over/under-fetching. GraphQL: client-specified queries, single endpoint, strongly typed schema, prevents over-fetching. gRPC: contract-first (Protocol Buffers), HTTP/2-based streaming, binary payloads, extremely fast, ideal for internal microservices.",
    tags: ["api-design", "rest", "graphql", "grpc"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_be_4",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is connection pooling and why is it important?",
    answer: "Creating database connections is computationally expensive. Connection pooling maintains a cache of open connections that are reused across incoming requests instead of opening/closing a connection per request. This prevents connection overhead from exhausting database limits and speeds up query execution.",
    tags: ["databases", "scaling", "performance"],
    createdAt: now,
  },
  {
    id: "iq_be_5",
    area: "backend",
    difficulty: "mid",
    category: "Security",
    question: "What are SQL injections and how do you prevent them?",
    answer: "SQL injection occurs when untrusted user input is concatenated directly into SQL queries, letting attackers execute arbitrary commands. Prevention: always use parameterized queries / prepared statements (which treat inputs as data, not executable code) or use ORMs that enforce parameterization by default.",
    tags: ["security", "sql", "backend"],
    createdAt: now,
  },
  {
    id: "iq_be_6",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is database normalization vs denormalization?",
    answer: "Normalization: organizing data to reduce redundancy and improve data integrity (split into multiple tables, link via keys). Denormalization: intentionally adding redundant data to tables to avoid expensive JOIN operations and optimize read performance. Normalization favors writes; denormalization favors reads.",
    tags: ["databases", "database-design"],
    createdAt: now,
  },
  {
    id: "iq_be_7",
    area: "backend",
    difficulty: "mid",
    category: "Caching",
    question: "How does Redis caching work and what are cache eviction policies?",
    answer: "Redis is an in-memory key-value store used for ultra-fast data retrieval. Eviction policies define how Redis behaves when it runs out of memory. Key policies: LRU (Least Recently Used), LFU (Least Frequently Used), FIFO (First In First Out), and volatile-lru (only evict keys with an explicit expiration TTL).",
    tags: ["caching", "redis", "system-design"],
    createdAt: now,
  },
  {
    id: "iq_be_8",
    area: "backend",
    difficulty: "mid",
    category: "Security",
    question: "Explain JWT vs Session-based authentication.",
    answer: "Sessions: stateful. Server creates a session in database/Redis and sends a cookie with sessionId to client. Server validates sessionId on every request. JWT: stateless. Server signs user info into a token and sends it to client. Client sends it in Authorization header. Server verifies token signature without DB lookups. Sessions are easier to revoke; JWTs require revocation/refresh flows.",
    tags: ["security", "auth", "jwt", "sessions"],
    createdAt: now,
  },
  {
    id: "iq_be_9",
    area: "backend",
    difficulty: "senior",
    category: "Security",
    question: "What is rate limiting and how do you implement it?",
    answer: "Rate limiting prevents API abuse by capping the number of requests a user/IP can make in a timeframe. Algorithms: Token Bucket, Leaky Bucket, Sliding Window Log. Implementation: middleware in application layer using Redis to track client request counts against rate limits dynamically.",
    tags: ["security", "rate-limiting", "redis"],
    createdAt: now,
  },
  {
    id: "iq_be_10",
    area: "backend",
    difficulty: "senior",
    category: "Databases",
    question: "What is a deadlock in databases and how do you prevent/resolve it?",
    answer: "A deadlock occurs when Transaction A holds a lock on Resource 1 and waits for Resource 2, while Transaction B holds a lock on Resource 2 and waits for Resource 1. Neither can proceed. Prevention: access tables in a consistent order, keep transactions short and simple, use appropriate isolation levels, and rely on db deadlock detection/timeouts.",
    tags: ["databases", "transactions", "concurrency"],
    createdAt: now,
  },

  // DevOps
  {
    id: "iq_dev_1",
    area: "devops",
    difficulty: "junior",
    category: "CI/CD",
    question: "What is CI/CD and why is it important?",
    answer: "CI (Continuous Integration): merging developer changes into a shared branch frequently, triggering automated builds and tests to catch bugs early. CD (Continuous Delivery/Deployment): automating the release of checked code to staging or production environments. Benefits: faster release cycle, lower risk, automated validation.",
    tags: ["ci-cd", "automation"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_2",
    area: "devops",
    difficulty: "junior",
    category: "Infrastructure",
    question: "What is Infrastructure as Code (IaC) and what are its benefits?",
    answer: "IaC is managing and provisioning infrastructure through machine-readable definition files (e.g., Terraform, Ansible) rather than manual configuration. Benefits: version-controlled configurations, repeatable setups, eliminates configuration drift, automated provisioning.",
    tags: ["infrastructure", "iac", "terraform"],
    createdAt: now,
  },
  {
    id: "iq_dev_3",
    area: "devops",
    difficulty: "junior",
    category: "Containers",
    question: "Explain the difference between virtualization (VMs) and containerization (Docker).",
    answer: "VMs: virtualize hardware, contain a full guest OS, hypervisor management, slow boot times, high memory footprint. Containers: virtualize the OS kernel, share the host OS kernel, run as isolated user space processes, lightweight, instant start times, highly portable.",
    tags: ["containers", "docker", "vms"],
    createdAt: now,
  },
  {
    id: "iq_dev_4",
    area: "devops",
    difficulty: "mid",
    category: "Networking",
    question: "What is a reverse proxy and how does it differ from a forward proxy?",
    answer: "Forward Proxy: sits in front of clients, forwards requests to external web servers (hides client identity). Reverse Proxy: sits in front of backend servers, routes client requests to appropriate servers (load balancing, SSL termination, caching). Clients only talk to the reverse proxy directly.",
    tags: ["networking", "nginx", "proxy"],
    createdAt: now,
  },
  {
    id: "iq_dev_5",
    area: "devops",
    difficulty: "mid",
    category: "Deployments",
    question: "What is blue-green deployment vs canary deployment?",
    answer: "Blue-Green: maintaining two identical environments. 'Blue' is live, 'Green' is idle where new release is deployed. Router switches traffic to Green. Rollback is instant. Canary: deploying new release to a small subset of servers / fraction of users (e.g., 5%), monitoring for errors, and slowly ramping up to 100%.",
    tags: ["deployments", "ci-cd"],
    createdAt: now,
  },
  {
    id: "iq_dev_6",
    area: "devops",
    difficulty: "mid",
    category: "Architecture",
    question: "What is the CAP theorem?",
    answer: "CAP states a distributed system can guarantee at most two out of three: Consistency (every read receives most recent write), Availability (every request receives a non-error response), Partition Tolerance (system continues to operate despite network partition). In real networks, partition tolerance is mandatory, so systems choose CP or AP.",
    tags: ["distributed-systems", "architecture"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_7",
    area: "devops",
    difficulty: "mid",
    category: "Networking",
    question: "What is a CDN and how does it work?",
    answer: "CDN (Content Delivery Network) is a distributed network of edge servers that cache static assets (images, CSS, JS) geographically closer to users. It reduces latency, offloads server traffic, and improves load speeds by serving files from the nearest edge node.",
    tags: ["networking", "caching", "performance"],
    createdAt: now,
  },
  {
    id: "iq_dev_8",
    area: "devops",
    difficulty: "mid",
    category: "Security",
    question: "How does HTTPS work? (Explain TLS handshake briefly).",
    answer: "HTTPS encrypts communications over HTTP using SSL/TLS. TLS Handshake: 1. Client hello (supported ciphers). 2. Server hello + Certificate (containing server public key). 3. Client validates certificate, generates pre-master secret, encrypts with server's public key. 4. Server decrypts with private key. 5. Both establish session keys for symmetric encryption.",
    tags: ["security", "networking", "https"],
    createdAt: now,
  },
  {
    id: "iq_dev_9",
    area: "devops",
    difficulty: "senior",
    category: "Containers",
    question: "What is Kubernetes (K8s) and what are its core components?",
    answer: "Kubernetes is a container orchestration platform. Core components: Pods (smallest deployable units), Nodes (machines), Deployments (manage replica sets and state), Services (expose pods via IP/load balancer), Kubelet (node agent), Control Plane (API server, scheduler, etcd database).",
    tags: ["kubernetes", "orchestration", "scaling"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_10",
    area: "devops",
    difficulty: "mid",
    category: "Scaling",
    question: "Explain horizontal vs vertical scaling.",
    answer: "Vertical: adding more resource capacity (CPU, RAM) to an existing server (scale up). Simpler but limited by hardware ceilings and introduces single points of failure. Horizontal: adding more server instances to the resource pool (scale out). Requires load balancers, enables infinite scale, handles failover.",
    tags: ["scaling", "system-design"],
    createdAt: now,
  },

  // Express / Nest / Python
  {
    id: "iq_fwb_1",
    area: "backend",
    difficulty: "junior",
    category: "Node.js Frameworks",
    question: "What is Express.js middleware and how does the request-response cycle work?",
    answer: "Express.js middleware are functions with access to the request (`req`), response (`res`), and the next middleware (`next`) in the application cycle. They execute code, modify `req`/`res`, and end the cycle or pass control using `next()`. If a middleware doesn't call `next()` or send a response, the request hangs.",
    tags: ["node", "express", "middleware"],
    createdAt: now,
  },
  {
    id: "iq_fwb_2",
    area: "backend",
    difficulty: "mid",
    category: "Node.js Frameworks",
    question: "What is the difference between NestJS and Express.js?",
    answer: "Express: unopinionated, minimal web framework for Node.js. Flexible but lacks built-in architecture guidelines. NestJS: opinionated, TypeScript-first framework built on top of Express (or Fastify) enforcing Angular-like architecture (modules, controllers, services). Built-in Dependency Injection, decorators, and module organization.",
    tags: ["node", "nestjs", "express", "architecture"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fwb_3",
    area: "backend",
    difficulty: "mid",
    category: "Django",
    question: "Explain Django's MTV architecture vs traditional MVC.",
    answer: "Django uses MTV: Model (data structure/DB definition), Template (HTML layout/presentation layer), View (controllers logic handling requests and returning responses). Traditional MVC maps to MTV: Model = Model, View = Template, Controller = View. The framework itself acts as the controller dispatching requests.",
    tags: ["python", "django", "architecture"],
    createdAt: now,
  },
  {
    id: "iq_fwb_4",
    area: "backend",
    difficulty: "mid",
    category: "Django",
    question: "What is Django's ORM and what is N+1 query problem?",
    answer: "Django ORM maps DB rows to Python objects. N+1 problem: querying a list of N objects and fetching a foreign key relationship per item, resulting in N+1 database queries. Solution: use `select_related()` (SQL JOIN for single relationships) or `prefetch_related()` (separate lookup query for multi-value relations).",
    tags: ["python", "django", "databases", "performance"],
    createdAt: now,
  },
  {
    id: "iq_fwb_5",
    area: "backend",
    difficulty: "mid",
    category: "FastAPI",
    question: "Why is FastAPI preferred for modern Python web APIs?",
    answer: "FastAPI: high performance (built on Starlette/Uvicorn), automatic interactive swagger docs (OpenAPI/Redoc), strict validation and serialization using Pydantic, native `async`/`await` support, clean dependency injection. Standardizes type-hinting which speeds up development.",
    tags: ["python", "fastapi", "performance"],
    createdAt: now,
  },

  // Vue & Svelte & Next.js
  {
    id: "iq_vue_1",
    area: "frontend",
    difficulty: "mid",
    category: "Vue.js",
    question: "What is the difference between Vue's Composition API and Options API?",
    answer: "Options API: organizes code by options (data, methods, computed, watch) — familiar but logic for one feature is scattered. Composition API (Vue 3): organizes code by logical concern using `setup()` and composables (reusable functions). Better TypeScript support, easier to extract/reuse logic. Both work in Vue 3; Composition API is recommended for new projects.",
    tags: ["vue", "composition-api", "options-api"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_vue_2",
    area: "frontend",
    difficulty: "mid",
    category: "Vue.js",
    question: "How does Vue 3's reactivity system work?",
    answer: "Vue 3 uses ES Proxy for reactivity. `reactive()` wraps an object in a Proxy that intercepts get/set to track dependencies and trigger updates. `ref()` wraps primitives in an object with a `.value` getter/setter. `computed()` creates lazy, cached derived values. `watch()` and `watchEffect()` run side effects when dependencies change. The tracking is automatic — accessing a reactive value inside a computed/watchEffect registers it as a dependency.",
    tags: ["vue", "reactivity", "proxy"],
    createdAt: now,
  },
  {
    id: "iq_vue_3",
    area: "frontend",
    difficulty: "junior",
    category: "Vue.js",
    question: "What is Pinia and why is it preferred over Vuex?",
    answer: "Pinia is the official Vue state management library (successor to Vuex). Benefits over Vuex: no mutations (just actions and state), full TypeScript support out of the box, simpler API (no namespaced modules), devtools support, composables-based design. Store: `defineStore('id', { state: () => ({}), getters: {}, actions: {} })`. Lightweight and tree-shakeable.",
    tags: ["vue", "pinia", "state-management"],
    createdAt: now,
  },
  {
    id: "iq_vue_4",
    area: "frontend",
    difficulty: "junior",
    category: "Vue.js",
    question: "What are Vue's key directives and what do they do?",
    answer: "v-if/v-else/v-else-if: conditionally renders (removes from DOM). v-show: toggles CSS display. v-for: list rendering (always add :key). v-bind (:): dynamically binds attributes/props. v-on (@): attaches event listeners. v-model: two-way data binding. v-slot: scoped slots. Rule: use v-show for frequent toggles (no DOM recreate); v-if for infrequent/conditional rendering.",
    tags: ["vue", "directives"],
    createdAt: now,
  },
  {
    id: "iq_vue_5",
    area: "frontend",
    difficulty: "mid",
    category: "Vue.js",
    question: "What is the difference between computed properties and watchers in Vue?",
    answer: "Computed: declarative derived values, cached until dependencies change, returns a value, use for derived UI data. Watch: imperative side effects when a value changes, no return value, use when you need to perform async operations or call APIs in response to state change. watchEffect: runs immediately and re-runs when any reactive dependency changes. Prefer computed over watch when possible.",
    tags: ["vue", "computed", "watch"],
    createdAt: now,
  },
  {
    id: "iq_sve_1",
    area: "frontend",
    difficulty: "mid",
    category: "Svelte",
    question: "How does Svelte fundamentally differ from React and Vue?",
    answer: "Svelte is a compiler, not a runtime framework. It compiles components to highly optimized vanilla JavaScript at build time — no virtual DOM, no runtime diffing. Updates are surgical direct DOM operations. Results: smaller bundle size, faster runtime performance, no overhead. Tradeoff: smaller ecosystem, no runtime introspection, compilation step required.",
    tags: ["svelte", "compiler", "performance"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_sve_2",
    area: "frontend",
    difficulty: "mid",
    category: "Svelte",
    question: "What are Svelte stores and how do they enable state sharing?",
    answer: "Svelte stores are observable objects with a subscribe method. Built-ins: writable(value), readable(value, start), derived(stores, fn). Any store can be used in any component — not just Svelte. The `$` prefix auto-subscribes and unsubscribes: `$count` in a template subscribes automatically. Custom stores wrap writable with additional logic. No provider/context needed for global state.",
    tags: ["svelte", "stores", "state"],
    createdAt: now,
  },
  {
    id: "iq_sve_3",
    area: "frontend",
    difficulty: "mid",
    category: "Svelte",
    question: "What are Svelte 5 Runes?",
    answer: "Runes (Svelte 5) replace the compiler magic with explicit reactive primitives: `$state()` for reactive state, `$derived()` for computed values, `$effect()` for side effects, `$props()` for component props. More explicit than Svelte 4's implicit reactivity (assigning to a variable = reactive). Better TypeScript support and clearer reactivity semantics. Similar intent to Vue's ref/computed/watchEffect but compiler-powered.",
    tags: ["svelte", "runes", "svelte5"],
    createdAt: now,
  },
  {
    id: "iq_nxt_1",
    area: "frontend",
    difficulty: "mid",
    category: "Next.js",
    question: "What is the difference between App Router and Pages Router in Next.js?",
    answer: "Pages Router (Next.js < 13): file-based routing in /pages, getServerSideProps/getStaticProps for data fetching, all components are client-side by default. App Router (Next.js 13+): file-based routing in /app, React Server Components by default, co-located layouts/loading/error files, Server Actions for mutations, streaming with Suspense. App Router is the recommended path for new projects.",
    tags: ["nextjs", "app-router", "pages-router"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_nxt_2",
    area: "frontend",
    difficulty: "mid",
    category: "Next.js",
    question: "What are React Server Components (RSC) and how do they differ from Client Components?",
    answer: "Server Components render exclusively on the server — they can fetch data directly (DB, APIs), import server-only modules, and never ship their code to the client. Client Components (`'use client'`) run in the browser and can use hooks, event handlers, browser APIs. RSCs can render Client Components but not vice versa. RSCs reduce JS bundle size and enable direct data access without API layers.",
    tags: ["nextjs", "rsc", "server-components"],
    createdAt: now,
  },
  {
    id: "iq_nxt_3",
    area: "frontend",
    difficulty: "mid",
    category: "Next.js",
    question: "What is Incremental Static Regeneration (ISR) in Next.js?",
    answer: "ISR lets you create or update static pages after build time without a full rebuild. Configure with `revalidate` in App Router (`export const revalidate = 60`). On-demand revalidation via `revalidatePath()` or `revalidateTag()`. Pages are served from cache and regenerated in the background when stale. Best for: e-commerce product pages, blog posts, dashboards that tolerate slight staleness.",
    tags: ["nextjs", "isr", "ssg", "caching"],
    createdAt: now,
  },
  {
    id: "iq_nxt_4",
    area: "frontend",
    difficulty: "mid",
    category: "Next.js",
    question: "What are Server Actions in Next.js?",
    answer: "Server Actions (Next.js 14+) are async functions that run on the server, callable from Client Components. Decorated with `'use server'`. Used for form submissions, mutations, database writes — eliminating the need for API routes for simple mutations. They integrate with React's form action pattern, support progressive enhancement, and can be used with `useFormState` / `useFormStatus` hooks.",
    tags: ["nextjs", "server-actions", "mutations"],
    createdAt: now,
  },

  // Frontend Core
  {
    id: "iq_fe_1",
    area: "frontend",
    difficulty: "junior",
    category: "Core Web",
    question: "What is the DOM and Virtual DOM? Explain the difference.",
    answer: "DOM (Document Object Model): structured browser representation of HTML. Editing DOM triggers expensive reflows/repaints. Virtual DOM: lightweight JavaScript representation of DOM. Changes are made to VDOM first, compared to real DOM (reconciliation), and only differences are surgically batch-updated.",
    tags: ["frontend", "dom", "vdom"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_2",
    area: "frontend",
    difficulty: "junior",
    category: "JavaScript",
    question: "Explain event delegation in JavaScript.",
    answer: "Event delegation: binding a single event listener to a parent element rather than individual child elements. Because of event bubbling (events rise up DOM tree), actions on children trigger the parent listener. Parent uses `event.target` to identify which child was clicked. Benefits: less memory, handles dynamically added elements automatically.",
    tags: ["javascript", "events"],
    createdAt: now,
  },
  {
    id: "iq_fe_3",
    area: "frontend",
    difficulty: "junior",
    category: "Core Web",
    question: "What is the difference between local storage, session storage, and cookies?",
    answer: "Local Storage: persists data with no expiration, browser-scoped, ~5MB capacity. Session Storage: persists data for tab lifetime, deleted on tab close, ~5MB capacity. Cookies: smaller ~4KB capacity, sent automatically with HTTP requests, has expiration options, security attributes (HttpOnly, Secure) for auth.",
    tags: ["frontend", "storage", "cookies"],
    createdAt: now,
  },
  {
    id: "iq_fe_4",
    area: "frontend",
    difficulty: "mid",
    category: "Core Web",
    question: "What is CORS and how does it work?",
    answer: "CORS (Cross-Origin Resource Sharing) is a security mechanism enforced by browsers. It blocks clients from loading resources from origins other than their own, unless the target server explicitly returns headers like `Access-Control-Allow-Origin: *`. Complex requests trigger an OPTIONS 'preflight' request first.",
    tags: ["security", "cors", "network"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_5",
    area: "frontend",
    difficulty: "junior",
    category: "CSS",
    question: "What is CSS specificity and how is it calculated?",
    answer: "Specificity determines which CSS rules apply to an element. Calculated as a 4-digit score: Inline styles (1000), IDs (100), Classes/pseudo-classes/attributes (10), Elements/pseudo-elements (1). Universal selector (*) has 0 specificity. `!important` overrides everything regardless of score.",
    tags: ["css", "specificity"],
    createdAt: now,
  },
  {
    id: "iq_fe_6",
    area: "frontend",
    difficulty: "senior",
    category: "JavaScript",
    question: "Explain the JavaScript event loop, microtasks, and macrotasks.",
    answer: "JS is single-threaded. Synchronous code executes first on Call Stack. When stack is empty, Event Loop checks queues. Microtask queue (Promises, queueMicrotask) has priority — all microtasks are drained before checking Macrotask queue (setTimeout, setInterval, user input). This repeats continuously.",
    tags: ["javascript", "concurrency", "event-loop"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_7",
    area: "frontend",
    difficulty: "mid",
    category: "JavaScript",
    question: "What are Closures in JavaScript and what is a practical use case?",
    answer: "A closure is the combination of a function bundled together with references to its surrounding state (lexical environment). It allows an inner function to access variables from an outer function even after the outer function has returned. Use cases: data privacy (private variables/methods), currying, and memoization.",
    tags: ["javascript", "closures"],
    createdAt: now,
  },
  {
    id: "iq_fe_8",
    area: "frontend",
    difficulty: "mid",
    category: "Core Web",
    question: "What is the difference between SSR (Server-Side Rendering) and SSG (Static Site Generation)?",
    answer: "SSR: pages generated dynamically on the server for *every request*. Good for dynamic data, but increases server response time. SSG: pages generated once at *build time*. Extremely fast to serve from CDN, but data is static until next build. ISR can be used to revalidate static pages on-demand.",
    tags: ["frontend", "rendering", "ssr", "ssg"],
    createdAt: now,
  },
  {
    id: "iq_fe_9",
    area: "frontend",
    difficulty: "junior",
    category: "CSS",
    question: "What is the box model in CSS?",
    answer: "The box model represents the layout of element structures: Content (text/images), Padding (clear area around content), Border (around padding), Margin (clear area outside border). `box-sizing: border-box` makes width/height include padding and borders, making layouts much more predictable.",
    tags: ["css", "box-model"],
    createdAt: now,
  },
  {
    id: "iq_fe_10",
    area: "frontend",
    difficulty: "mid",
    category: "JavaScript",
    question: "Explain debouncing vs throttling.",
    answer: "Debouncing: delays invoking a function until after N milliseconds have elapsed since the last time it was called (e.g., search autocomplete). Throttling: guarantees executing a function at most once every N milliseconds (e.g., scroll / resize event handler).",
    tags: ["javascript", "optimization"],
    createdAt: now,
  },

  // General core questions
  {
    id: "iq_gen_1",
    area: "general",
    difficulty: "mid",
    category: "Architecture",
    question: "What is the SOLID principles? Give a brief description of each.",
    answer: "S: Single Responsibility — one class, one reason to change. O: Open/Closed — open for extension, closed for modification. L: Liskov Substitution — subclasses must be substitutable for base classes. I: Interface Segregation — many specific interfaces > one general. D: Dependency Inversion — depend on abstractions, not concretions.",
    tags: ["architecture", "design-patterns"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_gen_2",
    area: "general",
    difficulty: "mid",
    category: "Systems",
    question: "What is the difference between concurrency and parallelism?",
    answer: "Concurrency: dealing with multiple things at once (structure) — e.g., Node.js event loop handles many requests on one thread by interleaving. Parallelism: doing multiple things simultaneously (execution) — requires multiple CPU cores. You can have concurrency without parallelism (single core multitasking).",
    tags: ["concurrency", "systems"],
    createdAt: now,
  },
  {
    id: "iq_gen_3",
    area: "general",
    difficulty: "senior",
    category: "System Design",
    question: "How do you approach a system design interview?",
    answer: "1. Clarify requirements (functional + non-functional: QPS, latency, scale). 2. Estimate scale (DAU, storage, bandwidth). 3. High-level design (API, data model, main components). 4. Deep dive on bottlenecks (DB choice, caching, sharding, CDN). 5. Discuss tradeoffs explicitly — no perfect answer. 6. Address reliability (replication, retries, circuit breakers).",
    tags: ["system-design", "interview"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_gen_4",
    area: "general",
    difficulty: "mid",
    category: "Architecture",
    question: "What is the difference between a monolith, microservices, and modular monolith?",
    answer: "Monolith: single deployable unit, simple to develop initially, hard to scale selectively. Microservices: independently deployable services, each owns its data; network overhead, distributed complexity. Modular monolith: clear internal module boundaries, single deployment — best of both worlds for most teams. Start modular monolith, extract services only when you have clear scaling needs.",
    tags: ["architecture", "microservices"],
    createdAt: now,
  },
  {
    id: "iq_gen_5",
    area: "general",
    difficulty: "junior",
    category: "Tools",
    question: "What is Git rebasing vs merging?",
    answer: "Merge: creates a merge commit preserving full branch history. Rebase: replays commits on top of target branch, creating a linear history. Rebase rewrites SHA hashes — never rebase shared/public branches. Use merge for feature → main; rebase for keeping feature branch up-to-date with main locally.",
    tags: ["git", "version-control"],
    createdAt: now,
  },

  // Testing
  {
    id: "iq_tst_1",
    area: "testing",
    difficulty: "junior",
    category: "Strategy",
    question: "What is the difference between unit, integration, and E2E tests?",
    answer: "Unit: test a single function/class in isolation (mock dependencies). Fast, cheap. Integration: test multiple units working together (DB, external services). Slower, catches interface bugs. E2E: test the full system as a user would (browser, real server). Slow, expensive, most confidence. Follow the Testing Pyramid: many unit, some integration, few E2E.",
    tags: ["testing", "strategy"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_tst_2",
    area: "testing",
    difficulty: "junior",
    category: "Concepts",
    question: "What is a test double (mock, stub, spy, fake)?",
    answer: "Test doubles replace real dependencies in tests. Stub: returns hardcoded data. Mock: stub + verifies it was called correctly. Spy: wraps real implementation + records calls. Fake: working lightweight implementation (in-memory DB). Use the least powerful double that makes the test meaningful.",
    tags: ["testing", "mocking"],
    createdAt: now,
  },
  {
    id: "iq_tst_3",
    area: "testing",
    difficulty: "mid",
    category: "Methodology",
    question: "What is Test-Driven Development (TDD) and what are its benefits?",
    answer: "TDD: Red → Green → Refactor. Write a failing test first, make it pass minimally, then refactor. Benefits: forces design thinking, creates living documentation, prevents over-engineering (YAGNI), catches regressions immediately. Criticism: slow for exploratory work, can lead to over-testing implementation details.",
    tags: ["tdd", "methodology"],
    createdAt: now,
  },
  {
    id: "iq_tst_4",
    area: "testing",
    difficulty: "mid",
    category: "Metrics",
    question: "What is code coverage and what are its limitations?",
    answer: "Coverage measures % of code lines/branches executed during tests. 100% coverage does NOT mean bug-free — tests may pass without meaningful assertions. It misses: wrong business logic, concurrency bugs, integration failures. Use coverage as a minimum bar (e.g., 80%) to find untested areas, not as a quality metric.",
    tags: ["testing", "coverage", "metrics"],
    createdAt: now,
  },
  {
    id: "iq_tst_5",
    area: "testing",
    difficulty: "mid",
    category: "JavaScript",
    question: "How do you test asynchronous code in JavaScript?",
    answer: "1. Return a Promise from the test. 2. Use `async/await`. 3. Use `done` callback (older Jest). 4. Use `vi.useFakeTimers()` / `jest.useFakeTimers()` to control time-based async. 5. For HTTP: use `msw` (Mock Service Worker) to intercept network requests. Always handle rejections — unhandled rejections can silently pass tests.",
    tags: ["javascript", "async", "testing"],
    createdAt: now,
  },
  {
    id: "iq_tst_6",
    area: "testing",
    difficulty: "mid",
    category: "Tooling",
    question: "What is the difference between Vitest and Jest?",
    answer: "Both are JavaScript test runners with similar APIs. Vitest: Vite-native, uses Vite's transform pipeline (fast, ESM-first, no config for modern stacks), watch mode is instant. Jest: mature, wider ecosystem, transpiles via Babel/tsc. For Vite/React projects Vitest is preferred; Jest for legacy CRA/Node projects.",
    tags: ["vitest", "jest", "tooling"],
    createdAt: now,
  },
  {
    id: "iq_tst_7",
    area: "testing",
    difficulty: "senior",
    category: "React",
    question: "How do you approach testing a React component that fetches data?",
    answer: "1. Use `@testing-library/react` (query by accessible role, not implementation). 2. Mock network with `msw` (Mock Service Worker) — intercepts at the network layer, not the fetch function. 3. Use `screen.findBy*` (async) to wait for data to render. 4. Test loading state, success state, and error state. Avoid testing internal state; test what the user sees.",
    tags: ["react", "testing-library", "msw"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_tst_8",
    area: "testing",
    difficulty: "senior",
    category: "React",
    question: "What is snapshot testing and when should you use or avoid it?",
    answer: "Snapshot tests serialize component output and compare against a stored file. Good for: detecting unintended UI changes in stable components, serializing complex data structures. Avoid when: snapshots are large/unreadable, updated blindly with `--updateSnapshot`, testing implementation details. Prefer explicit assertions for meaningful logic.",
    tags: ["testing", "snapshots", "react"],
    createdAt: now,
  },
  {
    id: "iq_tst_9",
    area: "testing",
    difficulty: "senior",
    category: "Tooling",
    question: "How do you write good E2E tests with Playwright/Cypress?",
    answer: "1. Use `data-testid` or ARIA roles — not CSS selectors. 2. Test critical user journeys, not every edge case. 3. Use fixtures/factories for test data; clean up after each test. 4. Run against a staging env with seeded data. 5. Parallelize across shards. 6. Retry flaky selectors with auto-wait (Playwright does this). 7. Screenshot on failure for debugging.",
    tags: ["e2e", "playwright", "cypress"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_tst_10",
    area: "testing",
    difficulty: "mid",
    category: "Concepts",
    question: "What is property-based testing?",
    answer: "Instead of example-based tests (specific inputs/outputs), you define properties that should hold for all inputs, and the framework generates hundreds of random inputs to find counterexamples. Tools: fast-check (JS), Hypothesis (Python), QuickCheck (Haskell). Great for: parsers, serializers, algorithms where invariants can be expressed. Hard to write for UIs.",
    tags: ["testing", "property-based"],
    createdAt: now,
  },
];
